LOCATION_MAPPING = {
    -- Clock Town
    [0x3469420000037] = {"@Clock Town/Spawn Area/Link's Inventory (Kokiri Sword)","@Clock Town Hints/Spawn Area Hints/Link's Inventory (Kokiri Sword) (Hint)"},
    [0x3469420056F0A] = {"@Clock Town/South Clock Town Clock Tower/Freestanding HP","@Clock Town Hints/South Clock Town Clock Tower Hints/Freestanding HP (Hint)"},
    [0x346942007028C] = {"@Clock Town/Keaton Quiz/Keaton Quiz","@Clock Town Hints/Keaton Quiz Hints/Keaton Quiz (Hint)"},
    [0x3469420040068] = {"@Clock Town/Clock Tower/Clock Tower Happy Mask Salesman #1","@Clock Town Hints/Clock Tower Hints/Clock Tower Happy Mask Salesman #1 (Hint)"},
    [0x3469420000078] = {"@Clock Town/Clock Tower/Clock Tower Happy Mask Salesman #2","@Clock Town Hints/Clock Tower Hints/Clock Tower Happy Mask Salesman #2 (Hint)"},
    [0x34694200701F2] = {"@Clock Town/Clock Town Postbox/Interact with Postman's Hat equipped","@Clock Town Hints/Clock Town Postbox Hints/Clock Town Postbox (Hint)"},
    [0x3469420000050] = {"@Clock Town/Clock Town Hide-and-Seek/Clock Town Hide-and-Seek","@Clock Town Hints/Clock Town Hide-and-Seek Hints/Clock Town Hide-and-Seek (Hint)"},
    [0x346942001007F] = {"@Clock Town/Laundry Pool Stray Fairy (Clock Town)/Laundry Pool Stray Fairy (Clock Town)","@Clock Town Hints/Laundry Pool Stray Fairy (Clock Town) Hints/Laundry Pool Stray Fairy (Clock Town) (Hint)"},
    [0x346942000008C] = {"@Clock Town/Laundry Pool Musician/Laundry Pool Musician (Night 1 - 2)","@Clock Town Hints/Laundry Pool Musician Hints/Laundry Pool Musician (Night 1 - 2) (Hint)"},
    [0x34694200000AB] = {"@Clock Town/Curiosity Shop Backroom/Laundry Pool Kafei's Request (Day 2, 4:30 PM)","@Clock Town Hints/Curiosity Shop Backroom Hints/Laundry Pool Kafei's Request (Day 2, 4:30 PM) (Hint)"},
    [0x3469420000080] = {"@Clock Town/Curiosity Shop Backroom/Laundry Pool Curiosity Shop Salesman #1 (Final Day, 1 PM - 9 PM)","@Clock Town Hints/Curiosity Shop Backroom Hints/Laundry Pool Curiosity Shop Salesman #1 (Final Day, 1 PM - 9 PM) (Hint)"},
    [0x34694200000A1] = {"@Clock Town/Curiosity Shop Backroom/Laundry Pool Curiosity Shop Salesman #2 (Final Day, 1 PM - 9 PM)","@Clock Town Hints/Curiosity Shop Backroom Hints/Laundry Pool Curiosity Shop Salesman #2 (Final Day, 1 PM - 9 PM) (Hint)"},
    [0x3469420066F00] = {"@Clock Town/South Clock Town Corner Chest/South Clock Town Corner Chest","@Clock Town Hints/South Clock Town Corner Chest Hints/South Clock Town Corner Chest (Hint)"},
    [0x3469420066F01] = {"@Clock Town/South Clock Town Final Day Tower Chest (Final Day)/South Clock Town Final Day Tower Chest","@Clock Town Hints/South Clock Town Final Day Tower Chest (Final Day) Hints/South Clock Town Final Day Tower Chest (Hint)"},
    [0x3469420066C0A] = {"@Clock Town/East Clock Town Archery Roof Chest/Jumping section starts near Bomber's Hideout entrance","@Clock Town Hints/East Clock Town Archery Roof Chest (Hint)/Jumping section starts near Bomber's Hideout entrance"},
    [0x346942000008F] = {"@Clock Town/Mayor's Residence (10 AM - 10 PM)/East Clock Town Mayor's Wife","@Clock Town Hints/Mayor's Residence (10 AM - 10 PM) Hints/East Clock Town Mayors Wife (Hint)"},
    [0x346942007026F] = {"@Clock Town/Mayor's Residence (10 AM - 10 PM)/East Clock Town Couple's Mask on Mayor","@Clock Town Hints/Mayor's Residence (10 AM - 10 PM) Hints/East Clock Town Couple's Mask on Mayor (Hint)"},
    [0x3469420000023] = {"@Clock Town/Town Shooting Gallery (6 AM - 10 PM)/East Clock Town Shooting Gallery 40-49 Points","@Clock Town Hints/Town Shooting Gallery (6 AM - 10 PM) Hints/East Clock Town Shooting Gallery 40-49 Points (Hint)"},
    [0x346942007011D] = {"@Clock Town/Town Shooting Gallery (6 AM - 10 PM)/East Clock Town Shooting Gallery Perfect 50 Points","@Clock Town Hints/Town Shooting Gallery (6 AM - 10 PM) Hints/East Clock Town Shooting Gallery Perfect 50 Points (Hint)"},
    [0x34694200800B5] = {"@Clock Town/Honey and Darling (6 AM - 10 PM)/East Clock Town Honey and Darling Any Day","@Clock Town Hints/Honey and Darling (6 AM - 10 PM) Hints/East Clock Town Honey and Darling Any Day (Hint)"},
    [0x34694200700B5] = {"@Clock Town/Honey and Darling (6 AM - 10 PM)/East Clock Town Honey and Darling All Days","@Clock Town Hints/Honey and Darling (6 AM - 10 PM) Hints/East Clock Town Honey and Darling All Days (Hint)"},
    [0x3469420061700] = {"@Clock Town/Treasure Game (6 AM - 10 PM)/East Clock Town Treasure Game Chest (Goron)","@Clock Town Hints/Treasure Game (6 AM - 10 PM) Hints/East Clock Town Treasure Game Chest (Goron) (Hint)"},
    [0x3469420062900] = {"@Clock Town/Bomber's Secret Hideout/Bomber's Hideout Chest","@Clock Town Hints/Bomber's Secret Hideout Hints/Bomber's Hideout Chest (Hint)"},
    [0x3469420000096] = {"@Termina Field/East Clock Town Astral Observatory/East Clock Town Astral Observatory","@Termina Field Hints/East Clock Town Astral Observatory Hints/East Clock Town Astral Observatory (Hint)"},
    [0x3469420056E0A] = {"@Clock Town/North Clock Town Tree HP/North Clock Town Tree HP","@Clock Town Hints/North Clock Town Tree HP Hints/North Clock Town Tree HP (Hint)"},
    [0x34694200801C9] = {"@Clock Town/Deku Playground/North Clock Town Deku Playground Any Day","@Clock Town Hints/Deku Playground Hints/North Clock Town Deku Playground Any Day (Hint)"},
    [0x34694200701C9] = {"@Clock Town/Deku Playground/North Clock Town Deku Playground All Days","@Clock Town Hints/Deku Playground Hints/North Clock Town Deku Playground All Days (Hint)"},
    [0x346942000008D] = {"@Clock Town/North Clock Town Save Old Lady/North Clock Town Save Old Lady (Night 1, 12 AM)","@Clock Town Hints/North Clock Town Save Old Lady Hints/North Clock Town Save Old Lady (Night 1, 12 AM) (Hint)"},
    [0x3469420030000] = {"@Clock Town/Clock Town Great Fairy/North Clock Town Great Fairy Reward","@Clock Town Hints/Clock Town Great Fairy Hints/North Clock Town Great Fairy Reward (Hint)"},
    [0x3469420000086] = {"@Clock Town/Clock Town Great Fairy/North Clock Town Great Fairy Reward (Transformation Mask)","@Clock Town Hints/Clock Town Great Fairy Hints/North Clock Town Great Fairy Reward (Transformation Mask) (Hint)"},
    [0x34694200701EF] = {"@Clock Town/West Clock Town Swordsman Expert Course/West Clock Town Swordsman Expert Course","@Clock Town Hints/West Clock Town Swordsman Expert Course Hints/West Clock Town Swordsman Expert Course (Hint)"},
    [0x346942007017D] = {"@Clock Town/Post Office/West Clock Town Postman Counting (Day 1: 3 PM - Midnight, Day 2: 5 PM - Midnight)","@Clock Town Hints/Post Office Hints/West Clock Town Postman Counting (Day 1: 3 PM - Midnight, Day 2: 5 PM - Midnight) (Hint)"},
    [0x346942007027B] = {"@Clock Town/West Clock Town Rosa Sisters/West Clock Town Rosa Sisters (Night 1 - 2)","@Clock Town Hints/West Clock Town Rosa Sisters Hints/West Clock Town Rosa Sisters (Night 1 - 2) (Hint)"},
    [0x3469420000008] = {"@Clock Town/Clock Town Bank/West Clock Town Bank 200 Rupees","@Clock Town Hints/Clock Town Bank Hints/West Clock Town Bank 200 Rupees (Hint)"},
    [0x3469420080177] = {"@Clock Town/Clock Town Bank/West Clock Town Bank 500 Rupees","@Clock Town Hints/Clock Town Bank Hints/West Clock Town Bank 500 Rupees (Hint)"},
    [0x3469420070177] = {"@Clock Town/Clock Town Bank/West Clock Town Bank 1000 Rupees","@Clock Town Hints/Clock Town Bank Hints/West Clock Town Bank 1000 Rupees (Hint)"},
    [0x3469420000084] = {"@Clock Town/Post Office/West Clock Town Priority Mail to Postman (Final Night)","@Clock Town Hints/Post Office Hints/West Clock Town Priority Mail to Postman (Final Night) (Hint)"},
    [0x3469420000097] = {"@Clock Town/South Clock Town Business Scrub/Moon's Tear Trade","@Clock Town Hints/South Clock Town Business Scrub Hints/Moon's Tear Trade (Hint)"},
    [0x346942000004C] = {"@Clock Town/Clock Tower/Top of Clock Tower (Ocarina of Time)","@Clock Town Hints/Clock Tower Hints/Top of Clock Tower (Ocarina of Time) (Hint)"},
    [0x3469420040067] = {"@Clock Town/Clock Tower/Top of Clock Tower (Song of Time)","@Clock Town Hints/Clock Tower Hints/Top of Clock Tower (Song of Time) (Hint)"},
    [0x34694200000A0] = {"@Clock Town/Stock Pot Inn/Stock Pot Inn Reservation (Day 1: from 1 PM to 4 PM)","@Clock Town Hints/Stock Pot Inn Hints/Stock Pot Inn Reservation (Day 1: from 1 PM to 4 PM) (Hint)"},
    [0x34694200000AA] = {"@Clock Town/Stock Pot Inn/Stock Pot Inn Midnight Meeting (Night 1: 11:30 PM)","@Clock Town Hints/Stock Pot Inn Hints/Stock Pot Inn Midnight Meeting (Night 1: 11:30 PM) (Hint)"},
    [0x3469420066100] = {"@Clock Town/Stock Pot Inn/Stock Pot Inn Upstairs Middle Room Chest","@Clock Town Hints/Stock Pot Inn Hints/Stock Pot Inn Upstairs Middle Room Chest (Hint)"},
    [0x3469420066101] = {"@Clock Town/Stock Pot Inn/Stock Pot Inn Employees Only Room Chest (Final Night)","@Clock Town Hints/Stock Pot Inn Hints/Stock Pot Inn Employees Only Room Chest (Final Night) (Hint)"},
    [0x346942007027D] = {"@Clock Town/Stock Pot Inn/Stock Pot Inn Midnight Toilet Hand","@Clock Town Hints/Stock Pot Inn Hints/Stock Pot Inn Midnight Toilet Hand (Hint)"},
    [0x3469420070243] = {"@Clock Town/Stock Pot Inn/Stock Pot Inn Granny Story #1","@Clock Town Hints/Stock Pot Inn Hints/Stock Pot Inn Granny Story #1 (Hint)"},
    [0x3469420080243] = {"@Clock Town/Stock Pot Inn/Stock Pot Inn Granny Story #2","@Clock Town Hints/Stock Pot Inn Hints/Stock Pot Inn Granny Story #2 (Hint)"},
    [0x3469420000085] = {"@Clock Town/Stock Pot Inn/Stock Pot Inn Anju and Kafei (Final Night 4:30 AM)","@Clock Town Hints/Stock Pot Inn Hints/Stock Pot Inn Anju and Kafei (Final Night 4:30 AM) (Hint)"},
    [0x3469420000083] = {"@Clock Town/Milk Bar (10 PM - 6 AM)/Milk Bar Show (Night 1 - 2)","@Clock Town Hints/Milk Bar (10 PM - 6 AM) Hints/Milk Bar Show (Night 1 - 2) (Hint)"},
    [0x346942000006F] = {"@Clock Town/Milk Bar (10 PM - 6 AM)/Priority Mail to Aroma (Final Night)","@Clock Town Hints/Milk Bar (10 PM - 6 AM) Hints/Priority Mail to Aroma (Final Night) (Hint)"},
    [0x3469420026392] = {"@Clock Town/Milk Bar (10 PM - 6 AM)/Milk Purchase","@Clock Town Hints,/Milk Bar (10 PM - 6 AM) Hints/Milk Purchase (Hint)"},
    [0x3469420000091] = {"@Clock Town/Milk Bar (10 PM - 6 AM)/Chateau Romani Purchase","@Clock Town Hints,/Milk Bar (10 PM - 6 AM) Hints/Chateau Romani Purchase (Hint)"},
    [0x346942009000A] = {"@Clock Town/Trading Post/Shop Item 1","@Clock Town Hints/Trading Post Hints/Shop Item 1 (Hint)"},
    [0x3469420090005] = {"@Clock Town/Trading Post/Shop Item 2","@Clock Town Hints/Trading Post Hints/Shop Item 2 (Hint)"},
    [0x3469420090006] = {"@Clock Town/Trading Post/Shop Item 3","@Clock Town Hints/Trading Post Hints/Shop Item 3 (Hint)"},
    [0x3469420090003] = {"@Clock Town/Trading Post/Shop Item 4","@Clock Town Hints/Trading Post Hints/Shop Item 4 (Hint)"},
    [0x3469420090007] = {"@Clock Town/Trading Post/Shop Item 5","@Clock Town Hints/Trading Post Hints/Shop Item 5 (Hint)"},
    [0x3469420090008] = {"@Clock Town/Trading Post/Shop Item 6","@Clock Town Hints/Trading Post Hints/Shop Item 6 (Hint)"},
    [0x3469420090009] = {"@Clock Town/Trading Post/Shop Item 7","@Clock Town Hints/Trading Post Hints/Shop Item 7 (Hint)"},
    [0x3469420090004] = {"@Clock Town/Trading Post/Shop Item 8","@Clock Town Hints/Trading Post Hints/Shop Item 8 (Hint)"},
    [0x3469420090012] = {"@Clock Town/Trading Post/Shop (Night) Item 1","@Clock Town Hints/Trading Post Hints/Shop (Night) Item 1 (Hint)"},
    [0x346942009000E] = {"@Clock Town/Trading Post/Shop (Night) Item 2","@Clock Town Hints/Trading Post Hints/Shop (Night) Item 2 (Hint)"},
    [0x3469420090011] = {"@Clock Town/Trading Post/Shop (Night) Item 3","@Clock Town Hints/Trading Post Hints/Shop (Night) Item 3 (Hint)"},
    [0x346942009000B] = {"@Clock Town/Trading Post/Shop (Night) Item 4","@Clock Town Hints/Trading Post Hints/Shop (Night) Item 4 (Hint)"},
    [0x3469420090010] = {"@Clock Town/Trading Post/Shop (Night) Item 5","@Clock Town Hints/Trading Post Hints/Shop (Night) Item 5 (Hint)"},
    [0x346942009000C] = {"@Clock Town/Trading Post/Shop (Night) Item 6","@Clock Town Hints/Trading Post Hints/Shop (Night) Item 6 (Hint)"},
    [0x346942009000F] = {"@Clock Town/Trading Post/Shop (Night) Item 7","@Clock Town Hints/Trading Post Hints/Shop (Night) Item 7 (Hint)"},
    [0x346942009000D] = {"@Clock Town/Trading Post/Shop (Night) Item 8","@Clock Town Hints/Trading Post Hints/Shop (Night) Item 8 (Hint)"},
    [0x346942009001A] = {"@Clock Town/Bomb Shop/Item 1","Clock Town Hints/Bomb Shop Hints/Item 1 (Hint)"},
    [0x3469420090019] = {"@Clock Town/Bomb Shop/Item 2","Clock Town Hints/Bomb Shop Hints/Item 2 (Hint)"},
    [0x3469420090017] = {"@Clock Town/Bomb Shop/Item 3","Clock Town Hints/Bomb Shop Hints/Item 3 (Hint)"},
    [0x3469420090018] = {"@Clock Town/Bomb Shop/Item 3 (Stop Thief)","Clock Town Hints/Bomb Shop Hints/Item 3 (Stop Thief) (Hint)"},
    [0x3469420024234] = {"@Clock Town/Bomb Shop/Powder Keg Goron","@Clock Town Hints/Bomb Shop Hints/Powder Keg Goron (Hint)"},
    [0x3469420090013] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Curiosity Shop Night 3 (Stop Thief)","@Clock Town Hints/Curiosity Shop (10 PM - 6 AM) Hints/Curiosity Shop Night 3 (Stop Thief) (Hint)"},
    [0x3469420090015] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Curiosity Shop Night 3 Thief Stolen Item","@Clock Town Hints/Curiosity Shop (10 PM - 6 AM) Hints/Curiosity Shop Night 3 Thief Stolen Item (Hint)"},
    [0x346942007C402] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Blue Rupee Trade (Half Milk)","@Clock Town Hints/Curiosity Shop (10 PM - 6 AM) Hints/Blue Rupee Trade (Half Milk) (Hint)"},
    [0x346942007C404] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Red Rupee Trade (Red potion or full milk)","@Clock Town Hints/Curiosity Shop (10 PM - 6 AM) Hints/Red Rupee Trade (Red potion or full milk) (Hint)"},
    [0x346942007C405] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Purple Rupee Trade (Poe)","@Clock Town Hints/Curiosity Shop (10 PM - 6 AM) Hints/Purple Rupee Trade (Poe) (Hint)"},
    [0x346942007C407] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Gold Rupee Trade (Big Poe)","@Clock Town Hints/Curiosity Shop (10 PM - 6 AM) Hints/Gold Rupee Trade (Big Poe) (Hint)"},
    [0x34694200000B4] = {"@Clock Town/Tingle Clock Town/Clock Town Map Purchase","@Clock Town Hints/Tingle Clock Town Hints/Clock Town Map Purchase (Hint)"},
    [0x3469420080239] = {"@Clock Town/West Clock Town Lottery/Win Any Day","@Clock Town Hints/West Clock Town Lottery Hints/Win Any Day (Hint)"},

    -- Termina Field
    [0x3469420062D02] = {"@Termina Field/South East Termina Field/Termina Stump Chest","@Termina Field Hints/South East Termina Field Hints/Termina Stump Chest (Hint)"},
    [0x3469420062D01] = {"@Termina Field/South East Termina Field/Termina Tall Grass Chest","@Termina Field Hints/South East Termina Field Hints/Termina Tall Grass Chest (Hint)"},
    [0x3469420062D00] = {"@Termina Field/Termina Underwater Chest/Termina Underwater Chest","@Termina Field Hints/Termina Underwater Chest Hints/Termina Underwater Chest (Hint)"},
    [0x346942006071F] = {"@Termina Field/South East Termina Field/Termina Tall Grass Grotto Chest","@Termina Field Hints/South East Termina Field Hints/Termina Tall Grass Grotto Chest (Hint)"},
    [0x3469420060704] = {"@Termina Field/Termina Field Peahat Grotto/Defeat Peahat (Daytime Only)","@Termina Field Hints/Termina Field Peahat Grotto Hints/Defeat Peahat (Daytime Only) (Hint)"},
    [0x3469420060700] = {"@Termina Field/Termina Dodongo Grotto Chest/Termina Dodongo Grotto Chest","@Termina Field Hints/Termina Dodongo Grotto Chest Hints/Termina Dodongo Grotto Chest (Hint)"},
    [0x346942006071A] = {"@Termina Field/Termina Ikana Pillar Grotto Chest/Termina Ikana Pillar Grotto Chest","@Termina Field Hints/Termina Ikana Pillar Grotto Chest Hints/Termina Ikana Pillar Grotto Chest (Hint)"},
    [0x3469420000089] = {"@Termina Field/Termina Northern Midnight Dancer/Termina Northern Midnight Dancer (Midnight - 6 AM)","@Termina Field Hints/Termina Northern Midnight Dancer Hints/Termina Northern Midnight Dancer (Midnight - 6 AM) (Hint)"},
    [0x3469420050702] = {"@Termina Field/Termina Bio Baba Grotto HP/Termina Bio Baba Grotto HP","@Termina Field Hints/Termina Bio Baba Grotto Hints/Termina Bio Baba Grotto HP (Hint)"},
    [0x34694200700EF] = {"@Termina Field/Termina Gossip Stones HP/Termina Gossip Stones HP","@Termina Field Hints/Termina Gossip Stones HP Hints/Termina Gossip Stones HP (Hint)"},
    [0x346942007024C] = {"@Termina Field/Termina Business Scrub Grotto/Termina Business Scrub Grotto HP","@Termina Field Hints/Termina Business Scrub Grotto Hints/Termina Business Scrub Grotto HP (Hint)"},
    [0x3469420BEEF14] = {"@Termina Field/Termina Log Bombable Grotto/Left Cow","@Termina Field Hints/Termina Log Bombable Grotto Hints/Left Cow (Hint)"},
    [0x3469420BEEF13] = {"@Termina Field/Termina Log Bombable Grotto/Right Cow","@Termina Field Hints/Termina Log Bombable Grotto Hints/Right Cow (Hint)"},

    -- Milk Road/Romani Ranch
    [0x34694200000B7] = {"@Romani Ranch/Tingle Milk Road/Romani Ranch Map Purchase","@Romani Ranch Hints/Tingle Milk Road Hints/Romani Ranch Map Purchase (Hint)"},
    [0x34694200000B8] = {"@Romani Ranch/Tingle Milk Road/Great Bay Map Purchase","@Romani Ranch Hints/Tingle Milk Road Hints/Great Bay Map Purchase (Hint)"},
    [0x3469420000081] = {"@Romani Ranch/Gorman Track/Race","@Romani Ranch Hints/Gorman Track Hints/Race (Hint)"},
    [0x3469420006792] = {"@Romani Ranch/Gorman Track/Purchase","@Romani Ranch Hints/Gorman Track Hints/Purchase (Hint)"},
    [0x346942000007F] = {"@Romani Ranch/Cucco Shack/Bremen Mask March Baby Cuccos","@Romani Ranch Hints/Cucco Shack Hints/Bremen Mask March Baby Cuccos (Hint)"},
    [0x3469420064100] = {"@Romani Ranch/Mamamu Yan's Doggy Racetrack/Rooftop Chest","@Romani Ranch Hints/Mamamu Yan's Doggy Racetrack Hints/Rooftop Chest (Hint)"},
    [0x3469420070117] = {"@Romani Ranch/Mamamu Yan's Doggy Racetrack/Dog Race","@Romani Ranch Hints/Mamamu Yan's Doggy Racetrack Hints/Dog Race (Hint)"},
    [0x3469420BEEF10] = {"@Romani Ranch/Romani Ranch Barn/Free Cow","@Romani Ranch Hints/Romani Ranch Barn Hints/Free Cow (Hint)"},
    [0x3469420BEEF11] = {"@Romani Ranch/Romani Ranch Barn/Stables Front Cow","@Romani Ranch Hints/Romani Ranch Barn Hints/Stables Front Cow (Hint)"},
    [0x3469420BEEF12] = {"@Romani Ranch/Romani Ranch Barn/Stables Back Cow","@Romani Ranch Hints/Romani Ranch Barn Hints/Stables Back Cow (Hint)"},
    [0x34694200000A5] = {"@Romani Ranch/Romani Ranch Outside/Romani Game","@Romani Ranch Hints/Romani Ranch Outside Hints/Romani Game (Hint)"},
    [0x3469420000060] = {"@Romani Ranch/Romani Ranch Outside/Defended Against Aliens","@Romani Ranch Hints/Romani Ranch Outside Hints/Defended Against Aliens (Hint)"},
    [0x3469420000082] = {"@Romani Ranch/Romani Ranch Outside/Helping Cremia","@Romani Ranch Hints/Romani Ranch Outside Hints/Helping Cremia (Hint)"},

    -- Southern Swamp
    [0x3469420054001] = {"@Southern Swamp/Road to Swamp Tree HP/Road to Swamp Tree HP","@Southern Swamp Hints/Road to Swamp Tree HP Hints/Road to Swamp Tree HP (Hint)"},
    [0x346942006071E] = {"@Southern Swamp/Road to Swamp Grotto Chest/Road to Swamp Grotto Chest","@Southern Swamp Hints/Road to Swamp Grotto Chest Hints/Road to Swamp Grotto Chest (Hint)"},
    [0x3469420000024] = {"@Southern Swamp/Swamp Shooting Gallery/Swamp Shooting Gallery 2120 Points","@Southern Swamp Hints/Swamp Shooting Gallery Hints/Swamp Shooting Gallery 2120 Points (Hint)"},
    [0x346942008011D] = {"@Southern Swamp/Swamp Shooting Gallery/Swamp Shooting Gallery 2180 Points","@Southern Swamp Hints/Swamp Shooting Gallery Hints/Swamp Shooting Gallery 2180 Points (Hint)"},
    [0x34694200000B5] = {"@Southern Swamp/Tingle Southern Swamp/Woodfall Map Purchase","@Southern Swamp Hints/Tingle Southern Swamp Hints/Woodfall Map Purchase (Hint)"},
    [0x3469420000098] = {"@Southern Swamp/Swamp Business Scrub/Southern Swamp Deku Trade","@Southern Swamp Hints/Swamp Business Scrub Hints/Southern Swamp Deku Trade (Hint)"},
    [0x3469420090135] = {"@Southern Swamp/Swamp Business Scrub/Southern Swamp Deku Scrub Purchase Beans","@Southern Swamp Hints/Swamp Business Scrub Hints/Southern Swamp Deku Scrub Purchase Beans (Hint)"},
    [0x346942005451E] = {"@Southern Swamp/Swamp Business Scrub/Southern Swamp Deku Trade Freestanding HP","@Southern Swamp Hints/Swamp Business Scrub Hints/Southern Swamp Deku Trade Freestanding HP (Hint)"},
    [0x3469420000059] = {"@Southern Swamp/Southern Swamp Healthy Witch Request/Southern Swamp Healthy Witch Request","@Southern Swamp Hints/Southern Swamp Healthy Witch Request Hints/Southern Swamp Healthy Witch Request (Hint)"},
    [0x3469420090002] = {"@Southern Swamp/Southern Swamp Witch Shop/Item 1","Southern Swamp Hints/Souther Swamp Witch Shop Hints/Item 1 (Hint)"},
    [0x3469420090001] = {"@Southern Swamp/Southern Swamp Witch Shop/Item 2","Southern Swamp Hints/Souther Swamp Witch Shop Hints/Item 2 (Hint)"},
    [0x3469420090000] = {"@Southern Swamp/Southern Swamp Witch Shop/Item 3","Southern Swamp Hints/Souther Swamp Witch Shop Hints/Item 3 (Hint)"},
    [0x346942006071C] = {"@Southern Swamp/Southern Swamp Mystery Woods Grotto Chest/Southern Swamp Mystery Woods Grotto Chest (Day 2)","@Southern Swamp Hints/Southern Swamp Mystery Woods Grotto Chest Hints/Southern Swamp Mystery Woods Grotto Chest (Day 2) (Hint)"},
    [0x3469420000043] = {"@Southern Swamp/Swamp Tourist Center/Southern Swamp Tour Witch Gift","@Southern Swamp Hints/Swamp Tourist Center Hints/Southern Swamp Tour Witch Gift (Hint)"},
    [0x346942006071D] = {"@Southern Swamp/Southern Swamp Near Swamphouse Grotto Chest/Southern Swamp Near Swamphouse Grotto Chest","@Southern Swamp Hints/Southern Swamp Near Swamphouse Grotto Chest Hints/Southern Swamp Near Swamphouse Grotto Chest (Hint)"},
    [0x346942004006A] = {"@Southern Swamp/Southern Swamp Song Tablet/Southern Swamp Song Tablet","@Southern Swamp Hints/Southern Swamp Song Tablet Hints/Southern Swamp Song Tablet (Hint)"},
    [0x3469420052B1E] = {"@Southern Swamp/Deku Palace HP/Deku Palace HP","@Southern Swamp Hints/Deku Palace HP Hints/Deku Palace HP (Hint)"},
    [0x3469420060705] = {"@Southern Swamp/Deku Palace Bean Grotto/Deku Palace Bean Grotto Chest","@Southern Swamp Hints/Deku Palace Bean Grotto Hints/Deku Palace Bean Grotto Chest (Hint)"},
    [0x34694200800A5] = {"@Southern Swamp/Deku Palace Bean Grotto/Deku Palace Bean Seller","@Southern Swamp Hints/Deku Palace Bean Grotto Hints/Deku Palace Bean Seller (Hint)"},
    [0x3469420040061] = {"@Southern Swamp/Deku Palace Monkey Song/Deku Palace Monkey Song","@Southern Swamp Hints/Deku Palace Monkey Song Hints/Deku Palace Monkey Song (Hint)"},
    [0x346942000008E] = {"@Southern Swamp/Deku Shrine/Deku Palace Butler Race","@Southern Swamp Hints/Deku Shrine Hints/Deku Palace Butler Race (Hint)"},
    [0x3469420064602] = {"@Southern Swamp/Woodfall/Woodfall Near Owl Statue Chest","@Southern Swamp Hints/Woodfall Hints/Woodfall Near Owl Statue Chest (Hint)"},
    [0x3469420064601] = {"@Southern Swamp/Woodfall/Woodfall After Great Fairy Cave Chest","@Southern Swamp Hints/Woodfall Hints/Woodfall After Great Fairy Cave Chest (Hint)"},
    [0x3469420064600] = {"@Southern Swamp/Woodfall/Woodfall Near Swamp Entrance Chest","@Southern Swamp Hints/Woodfall Hints/Woodfall Near Swamp Entrance Chest (Hint)"},
    [0x3469420030001] = {"@Southern Swamp/Woodfall/Woodfall Great Fairy Reward","@Southern Swamp Hints/Woodfall Hints/Woodfall Great Fairy Reward (Hint)"},
    [0x3469420070168] = {"@Southern Swamp/Swamp Tourist Center/Tour Witch Target Shooting","@Southern Swamp Hints/Swamp Tourist Center Hints/Tour Witch Target Shooting (Hint)"},

    -- Swamp Spider House
    [0x346942006271E] = {"@Dungeons/Swamp Spider House/Swamphouse First Room Pot Near Entrance Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse First Room Pot Near Entrance Token (Hint)"},
    [0x3469420062708] = {"@Dungeons/Swamp Spider House/Swamphouse First Room Crawling In Water Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse First Room Crawling In Water Token (Hint)"},
    [0x346942006270F] = {"@Dungeons/Swamp Spider House/Swamphouse First Room Crawling Right Column Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse First Room Crawling Right Column Token (Hint)"},
    [0x3469420062713] = {"@Dungeons/Swamp Spider House/Swamphouse First Room Crawling Left Column Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse First Room Crawling Left Column Token (Hint)"},
    [0x3469420062700] = {"@Dungeons/Swamp Spider House/Swamphouse First Room Against Far Wall Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse First Room Against Far Wall Token (Hint)"},
    [0x3469420062709] = {"@Dungeons/Swamp Spider House/Swamphouse First Room Left Bugpatch Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse First Room Left Bugpatch Token (Hint)"},
    [0x346942006270C] = {"@Dungeons/Swamp Spider House/Swamphouse First Room Right Bugpatch Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse First Room Right Bugpatch Token (Hint)"},
    [0x346942006270B] = {"@Dungeons/Swamp Spider House/Swamphouse First Room Upper Right Bugpatch Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse First Room Upper Right Bugpatch Token (Hint)"},
    [0x346942006270A] = {"@Dungeons/Swamp Spider House/Swamphouse Monument Room Left Crate Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Monument Room Left Crate Token (Hint)"},
    [0x346942006271B] = {"@Dungeons/Swamp Spider House/Swamphouse Monument Room Right Crate Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Monument Room Right Crate Token (Hint)"},
    [0x346942006270D] = {"@Dungeons/Swamp Spider House/Swamphouse Monument Room Crawling Wall Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Monument Room Crawling Wall Token (Hint)"},
    [0x346942006270E] = {"@Dungeons/Swamp Spider House/Swamphouse Monument Room Crawling On Monument Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Monument Room Crawling On Monument Token (Hint)"},
    [0x3469420062702] = {"@Dungeons/Swamp Spider House/Swamphouse Monument Room Behind Torch Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Monument Room Behind Torch Token (Hint)"},
    [0x3469420062717] = {"@Dungeons/Swamp Spider House/Swamphouse Pottery Room Beehive #1 Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Pottery Room Beehive #1 Token (Hint)"},
    [0x346942006271C] = {"@Dungeons/Swamp Spider House/Swamphouse Pottery Room Beehive #2 Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Pottery Room Beehive #2 Token (Hint)"},
    [0x3469420062705] = {"@Dungeons/Swamp Spider House/Swamphouse Pottery Room Small Pot Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Pottery Room Small Pot Token (Hint)"},
    [0x3469420062710] = {"@Dungeons/Swamp Spider House/Swamphouse Pottery Room Left Large Pot Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Pottery Room Left Large Pot Token (Hint)"},
    [0x3469420062711] = {"@Dungeons/Swamp Spider House/Swamphouse Pottery Room Right Large Pot Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Pottery Room Right Large Pot Token (Hint)"},
    [0x3469420062714] = {"@Dungeons/Swamp Spider House/Swamphouse Pottery Room Behind Vines Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Pottery Room Behind Vines Token (Hint)"},
    [0x3469420062716] = {"@Dungeons/Swamp Spider House/Swamphouse Pottery Room Upper Wall Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Pottery Room Upper Wall Token (Hint)"},
    [0x3469420062719] = {"@Dungeons/Swamp Spider House/Swamphouse Golden Room Crawling Left Wall Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Golden Room Crawling Left Wall Token (Hint)"},
    [0x3469420062704] = {"@Dungeons/Swamp Spider House/Swamphouse Golden Room Crawling Right Column Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Golden Room Crawling Right Column Token (Hint)"},
    [0x3469420062701] = {"@Dungeons/Swamp Spider House/Swamphouse Golden Room Against Far Wall Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Golden Room Against Far Wall Token (Hint)"},
    [0x3469420062712] = {"@Dungeons/Swamp Spider House/Swamphouse Golden Room Beehive Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Golden Room Beehive Token (Hint)"},
    [0x3469420062707] = {"@Dungeons/Swamp Spider House/Swamphouse Tree Room Tall Grass #1 Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Tree Room Tall Grass #1 Token (Hint)"},
    [0x3469420062706] = {"@Dungeons/Swamp Spider House/Swamphouse Tree Room Tall Grass #2 Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Tree Room Tall Grass #2 Token (Hint)"},
    [0x3469420062715] = {"@Dungeons/Swamp Spider House/Swamphouse Tree Room Tree #1 Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Tree Room Tree #1 Token (Hint)"},
    [0x3469420062718] = {"@Dungeons/Swamp Spider House/Swamphouse Tree Room Tree #2 Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Tree Room Tree #2 Token (Hint)"},
    [0x346942006271D] = {"@Dungeons/Swamp Spider House/Swamphouse Tree Room Tree #3 Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Tree Room Tree #3 Token (Hint)"},
    [0x346942006271A] = {"@Dungeons/Swamp Spider House/Swamphouse Tree Room Beehive Token","@Dungeons Hints/Swamp Spider House Hints/Swamphouse Tree Room Beehive Token (Hint)"},
    [0x346942000008A] = {"@Dungeons/Swamp Spider House/Collect 30 Tokens","@Dungeons Hints/Swamp Spider House Hints/Collect 30 Tokens (Hint)"},

    -- Woodfall Temple
    [0x3469420061B18] = {"@Dungeons/Woodfall Temple/Woodfall Temple Entrance Chest","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Entrance Chest (Hint)"},
    [0x3469420061B01] = {"@Dungeons/Woodfall Temple/Woodfall Temple Moving Flower Platform Room Chest","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Moving Flower Platform Room Chest (Hint)"},
    [0x3469420061B1D] = {"@Dungeons/Woodfall Temple/Woodfall Temple Gagwab Chest","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Gagwab Chest (Hint)"},
    [0x3469420061B1C] = {"@Dungeons/Woodfall Temple/Woodfall Temple Dragonfly Chest","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Dragonfly Chest (Hint)"},
    [0x3469420061B19] = {"@Dungeons/Woodfall Temple/Woodfall Temple Black Boe Room Chest","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Black Boe Room Chest (Hint)"},
    [0x3469420061B17] = {"@Dungeons/Woodfall Temple/Woodfall Temple Wooden Flower Switch Chest","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Wooden Flower Switch Chest (Hint)"},
    [0x3469420061B1B] = {"@Dungeons/Woodfall Temple/Woodfall Temple Dinolfos Chest","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Dinolfos Chest (Hint)"},
    [0x3469420061B1E] = {"@Dungeons/Woodfall Temple/Woodfall Temple Boss Key Chest","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Boss Key Chest (Hint)"},
    [0x3469420011B2B] = {"@Dungeons/Woodfall Temple/Woodfall Temple Entrance Freestanding SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Entrance Freestanding SF (Hint)"},
    [0x3469420011B2E] = {"@Dungeons/Woodfall Temple/Woodfall Temple Wooden Flower Deku Baba SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Wooden Flower Deku Baba SF (Hint)"},
    [0x3469420011B1C] = {"@Dungeons/Woodfall Temple/Woodfall Temple Wooden Flower Pot SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Wooden Flower Pot SF (Hint)"},
    [0x3469420011B1E] = {"@Dungeons/Woodfall Temple/Woodfall Temple Moving Flower Platform Room Beehive SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Moving Flower Platform Room Beehive SF (Hint)"},
    [0x3469420011B30] = {"@Dungeons/Woodfall Temple/Woodfall Temple Wooden Flower Bubble SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Wooden Flower Bubble SF (Hint)"},
    [0x3469420011B31] = {"@Dungeons/Woodfall Temple/Woodfall Temple Push Block Skulltula SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Push Block Skulltula SF (Hint)"},
    [0x3469420011B2F] = {"@Dungeons/Woodfall Temple/Woodfall Temple Push Block Bubble SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Push Block Bubble SF (Hint)"},
    [0x3469420011B1D] = {"@Dungeons/Woodfall Temple/Woodfall Temple Push Block Beehive SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Push Block Beehive SF (Hint)"},
    [0x3469420011B2A] = {"@Dungeons/Woodfall Temple/Woodfall Temple Final Room Right Lower Platform SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Final Room Right Lower Platform SF (Hint)"},
    [0x3469420011B32] = {"@Dungeons/Woodfall Temple/Woodfall Temple Final Room Right Upper Platform SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Final Room Right Upper Platform SF (Hint)"},
    [0x3469420011B2C] = {"@Dungeons/Woodfall Temple/Woodfall Temple Final Room Left Upper Platform SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Final Room Left Upper Platform SF (Hint)"},
    [0x3469420011B2D] = {"@Dungeons/Woodfall Temple/Woodfall Temple Final Room Bubble SF","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Final Room Bubble SF (Hint)"},
    [0x3469420051F00] = {"@Dungeons/Woodfall Temple/Woodfall Temple Heart Container","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Heart Container (Hint)"},
    [0x3469420000055] = {"boss_odolwa_hosted","@Dungeons Hints/Woodfall Temple Hints/Woodfall Temple Odolwa's Remains (Hint)"},

    -- Snowhead
    [0x3469420065A00] = {"@Snowhead/Mountain Village/Spring Waterfall Chest","@Snowhead Hints/Mountain Village Hints/Spring Waterfall Chest (Hint)"},
    [0x346942006071B] = {"@Snowhead/Mountain Village/Spring Ramp Grotto","@Snowhead Hints/Mountain Village Hints/Spring Ramp Grotto (Hint)"},
    [0x3469420000079] = {"@Snowhead/Mountain Village/Invisible Ladder Cave Healing Invisible Goron","@Snowhead Hints/Mountain Village Hints/Invisible Ladder Cave Healing Invisible Goron (Hint)"},
    [0x3469420000088] = {"@Snowhead/Mountain Village/Feeding Freezing Goron","@Snowhead Hints/Mountain Village Hints/Feeding Freezing Goron (Hint)"},
    [0x3469420070022] = {"@Snowhead/Mountain Village/Don Gero Mask Frog Song HP","@Snowhead Hints/Mountain Village Hints/Don Gero Mask Frog Song HP (Hint)"},
    [0x34694200000B6] = {"@Southern Swamp/Tingle Southern Swamp/Snowhead Map Purchase","@Southern Swamp Hints/Tingle Southern Swamp Hints/Snowhead Map Purchase (Hint)"},
    [0x3469420065E00] = {"@Snowhead/Twin Islands/Spring Underwater Cave Chest","@Snowhead Hints/Twin Islands Hints/Spring Underwater Cave Chest (Hint)"},
    [0x3469420065E06] = {"@Snowhead/Twin Islands/Spring Underwater Near Ramp Chest","@Snowhead Hints/Twin Islands Hints/Spring Underwater Near Ramp Chest (Hint)"},
    [0x3469420060719] = {"@Snowhead/Twin Islands/Ramp Grotto Chest","@Snowhead Hints/Twin Islands Hints/Ramp Grotto Chest (Hint)"},
    [0x34694200001AD] = {"@Snowhead/Twin Islands/Goron Elder Request","@Snowhead Hints/Twin Islands Hints/Goron Elder Request (Hint)"},
    [0x3469420060702] = {"@Snowhead/Twin Islands/Hot Water Grotto Chest","@Snowhead Hints/Twin Islands Hints/Hot Water Grotto Chest (Hint)"},
    [0x3469420060701] = {"@Snowhead/Lens Cave/Center Chest","@Snowhead Hints/Lens Cave Hints/Center Chest (Hint)"},
    [0x3469420060703] = {"@Snowhead/Lens Cave/Invisible Chest","@Snowhead Hints/Lens Cave Hints/Invisible Chest (Hint)"},
    [0x3469420060706] = {"@Snowhead/Lens Cave/Rock Chest","@Snowhead Hints/Lens Cave Hints/Rock Chest (Hint)"},
    [0x34694200000AD] = {"@Snowhead/Goron Village/Baby Goron Lullaby","@Snowhead Hints/Goron Village Hints/Baby Goron Lullaby (Hint)"},
    [0x346942009001E] = {"@Snowhead/Goron Village/Shop Item 1","@Snowhead Hints/Goron Village Hints/Shop Item 1 (Hint)"},
    [0x346942009001F] = {"@Snowhead/Goron Village/Shop Item 2","@Snowhead Hints/Goron Village Hints/Shop Item 2 (Hint)"},
    [0x3469420090020] = {"@Snowhead/Goron Village/Shop Item 3","@Snowhead Hints/Goron Village Hints/Shop Item 3 (Hint)"},
    [0x3469420090021] = {"@Snowhead/Goron Village/Shop (Spring) Item 1","@Snowhead Hints/Goron Village Hints/Shop (Spring) Item 1 (Hint)"},
    [0x3469420090022] = {"@Snowhead/Goron Village/Shop (Spring) Item 2","@Snowhead Hints/Goron Village Hints/Shop (Spring) Item 2 (Hint)"},
    [0x3469420090023] = {"@Snowhead/Goron Village/Shop (Spring) Item 3","@Snowhead Hints/Goron Village Hints/Shop (Spring) Item 3 (Hint)"},
    [0x346942009011D] = {"@Snowhead/Goron Village/Deku Scrub Purchase Bomb Bag","@Snowhead Hints/Goron Village Hints/Deku Scrub Purchase Bomb Bag (Hint)"},
    [0x3469420000099] = {"@Snowhead/Goron Village/Deku Trade","@Snowhead Hints/Goron Village Hints/Deku Trade (Hint)"},
    [0x3469420054D1E] = {"@Snowhead/Goron Village/Deku Trade Freestanding HP","@Snowhead Hints/Goron Village Hints/Deku Trade Freestanding HP (Hint)"},
    [0x3469420000034] = {"@Snowhead/Goron Village/Powder Keg Goron Reward","@Snowhead Hints/Goron Village Hints/Powder Keg Goron Reward (Hint)"},
    [0x346942005481E] = {"@Snowhead/Goron Village/Deku Trade Freestanding HP (Spring)","@Snowhead Hints/Goron Village Hints/Deku Trade Freestanding HP (Spring) (Hint)"},
    [0x3469420060713] = {"@Snowhead/Path to Snowhead/Grotto Chest","Snowhead Hints/Path to Snowhead Hints/Grotto Chest (Hint)"},
    [0x3469420055B08] = {"@Snowhead/Path to Snowhead/Scarecrow Pillar HP","Snowhead Hints/Path to Snowhead Hints/Scarecrow Pillar HP (Hint)"},
    [0x3469420030002] = {"@Snowhead/Snowhead/Snowhead Great Fairy Reward","@Snowhead Hints/Snowhead Hints/Snowhead Great Fairy Reward (Hint)"},

    -- Snowhead Temple
    [0x3469420062101] = {"@Dungeons/Snowhead Temple/Initial Runway Ice Blowers Chest","@Dungeons Hints/Snowhead Temple Hints/Initial Runway Ice Blowers Chest (Hint)"},
    [0x346942001212F] = {"@Dungeons/Snowhead Temple/Initial Runway Under Platform Bubble SF","@Dungeons Hints/Snowhead Temple Hints/Initial Runway Under Platform Bubble SF (Hint)"},
    [0x3469420012130] = {"@Dungeons/Snowhead Temple/Initial Runway Tower Bubble SF","@Dungeons Hints/Snowhead Temple Hints/Initial Runway Tower Bubble SF (Hint)"},
    [0x346942006211C] = {"@Dungeons/Snowhead Temple/Light Blue Door Center Chest","@Dungeons Hints/Snowhead Temple Hints/Light Blue Door Center Chest (Hint)"},
    [0x3469420062119] = {"@Dungeons/Snowhead Temple/Light Blue Door Upper Chest","@Dungeons Hints/Snowhead Temple Hints/Light Blue Door Upper Chest (Hint)"},
    [0x346942001211E] = {"@Dungeons/Snowhead Temple/Light Blue Door Near Bombable Stairs Box SF","@Dungeons Hints/Snowhead Temple Hints/Light Blue Door Near Bombable Stairs Box SF (Hint)"},
    [0x3469420062115] = {"@Dungeons/Snowhead Temple/Orange Door Upper Chest","@Dungeons Hints/Snowhead Temple Hints/Orange Door Upper Chest (Hint)"},
    [0x3469420062103] = {"@Dungeons/Snowhead Temple/Orange Door Behind Block Chest","@Dungeons Hints/Snowhead Temple Hints/Orange Door Behind Block Chest (Hint)"},
    [0x3469420062118] = {"@Dungeons/Snowhead Temple/Green Door Ice Blowers Chest","@Dungeons Hints/Snowhead Temple Hints/Green Door Ice Blowers Chest (Hint)"},
    [0x3469420062114] = {"@Dungeons/Snowhead Temple/Bottom Floor Switch Chest","@Dungeons Hints/Snowhead Temple Hints/Bottom Floor Switch Chest (Hint)"},
    [0x3469420062117] = {"@Dungeons/Snowhead Temple/Column Room 2F Hidden Chest","@Dungeons Hints/Snowhead Temple Hints/Column Room 2F Hidden Chest (Hint)"},
    [0x346942006211D] = {"@Dungeons/Snowhead Temple/Elevator Room Lower Chest","@Dungeons Hints/Snowhead Temple Hints/Elevator Room Lower Chest (Hint)"},
    [0x3469420062113] = {"@Dungeons/Snowhead Temple/Elevator Room Invisible Platform Chest","@Dungeons Hints/Snowhead Temple Hints/Elevator Room Invisible Platform Chest (Hint)"},
    [0x3469420012132] = {"@Dungeons/Snowhead Temple/Elevator Freestanding SF","@Dungeons Hints/Snowhead Temple Hints/Elevator Freestanding SF (Hint)"},
    [0x3469420062104] = {"@Dungeons/Snowhead Temple/Upstairs 2F Icicle Room Snowball Chest","@Dungeons Hints/Snowhead Temple Hints/Upstairs 2F Icicle Room Snowball Chest (Hint)"},
    [0x3469420062116] = {"@Dungeons/Snowhead Temple/Upstairs 2F Icicle Room Hidden Chest","@Dungeons Hints/Snowhead Temple Hints/Upstairs 2F Icicle Room Hidden Chest (Hint)"},
    [0x346942001212C] = {"@Dungeons/Snowhead Temple/Timed Switch Room Bubble SF","@Dungeons Hints/Snowhead Temple Hints/Timed Switch Room Bubble SF (Hint)"},
    [0x346942006211B] = {"@Dungeons/Snowhead Temple/1st Wizzrobe Chest","@Dungeons Hints/Snowhead Temple Hints/1st Wizzrobe Chest (Hint)"},
    [0x346942001212B] = {"@Dungeons/Snowhead Temple/Snowmen Bubble SF","@Dungeons Hints/Snowhead Temple Hints/Snowmen Bubble SF (Hint)"},
    [0x3469420012131] = {"@Dungeons/Snowhead Temple/Dinolfos Room First SF","@Dungeons Hints/Snowhead Temple Hints/Dinolfos Room First SF (Hint)"},
    [0x346942001212D] = {"@Dungeons/Snowhead Temple/Dinolfos Room Second SF","@Dungeons Hints/Snowhead Temple Hints/Dinolfos Room Second SF (Hint)"},
    [0x346942006211E] = {"@Dungeons/Snowhead Temple/2nd Wizzrobe Chest","@Dungeons Hints/Snowhead Temple Hints/2nd Wizzrobe Chest (Hint)"},
    [0x3469420054400] = {"@Dungeons/Snowhead Temple/Heart Container","@Dungeons Hints/Snowhead Temple Hints/Heart Container (Hint)"},
    [0x3469420000056] = {"@Dungeons/Snowhead Temple/Goht's Remains","@Dungeons Hints/Snowhead Temple Hints/Goht's Remains (Hint)"},

    -- Great Bay Coast
    [0x346942000007A] = {"@Great Bay/Great Bay Coast/Healing Zora","@Great Bay Hints/Great Bay Coast Hints/Healing Zora (Hint)"},
    [0x3469420060717] = {"@Great Bay/Great Bay Coast/Behind Fisherman's Hut Grotto Chest","@Great Bay Hints/Great Bay Coast Hints/Behind Fisherman's Hut Grotto Chest (Hint)"},
    [0x34694200000AC] = {"@Great Bay/Great Bay Coast/Marine Research Lab Zora Egg Delivery Song","@Great Bay Hints/Great Bay Coast Hints/Marine Research Lab Zora Egg Delivery Song (Hint)"},
    [0x34694200701D9] = {"@Great Bay/Great Bay Coast/Marine Research Lab Feeding Fish","@Great Bay Hints/Great Bay Coast Hints/Marine Research Lab Feeding Fish (Hint)"},
    [0x3469420BEEF16] = {"@Great Bay/Great Bay Coast/Ledge Grotto Left Cow","@Great Bay Hints/Great Bay Coast Hints/Ledge Grotto Left Cow (Hint)"},
    [0x3469420BEEF15] = {"@Great Bay/Great Bay Coast/Ledge Grotto Right Cow","@Great Bay Hints/Great Bay Coast Hints/Ledge Grotto Right Cow (Hint)"},
    [0x3469420053705] = {"@Great Bay/Great Bay Coast/Scarecrow Ledge HP","@Great Bay Hints/Great Bay Coast Hints/Scarecrow Ledge HP (Hint)"},
    [0x3469420070292] = {"@Great Bay/Great Bay Coast/Great Bay (Cleared) Fisherman Island Game HP","@Great Bay Hints/Great Bay Coast Hints/Great Bay (Cleared) Fisherman Island Game HP (Hint)"},

    -- Zora Cape
    [0x3469420053807] = {"@Great Bay/Zora Cape/Underwater Like-Like HP","@Great Bay Hints/Zora Cape Hints/Underwater Like-Like HP (Hint)"},
    [0x3469420063800] = {"@Great Bay/Zora Cape/Underwater Chest","@Great Bay Hints/Zora Cape Hints/Underwater Chest (Hint)"},
    [0x3469420072806] = {"@Great Bay/Zora Cape/Pot Game Silver Rupee","@Great Bay Hints/Zora Cape Hints/Pot Game Silver Rupee (Hint)"},
    [0x3469420063801] = {"@Great Bay/Zora Cape/Upper Chest","@Great Bay Hints/Zora Cape Hints/Upper Chest (Hint)"},
    [0x3469420063802] = {"@Great Bay/Zora Cape/Tree Chest","@Great Bay Hints/Zora Cape Hints/Tree Chest (Hint)"},
    [0x3469420060715] = {"@Great Bay/Zora Cape/Near Great Fairy Grotto Chest","@Great Bay Hints/Zora Cape Hints/Near Great Fairy Grotto Chest (Hint)"},
    [0x3469420030003] = {"@Great Bay/Zora Cape/Great Bay Great Fairy Reward","@Great Bay Hints/Zora Cape Hints/Great Bay Great Fairy Reward (Hint)"},
    [0x346942009018D] = {"@Great Bay/Zora Cape/Beaver Bros. Race Bottle Reward","@Great Bay Hint/Zora Cape Hints/Beaver Bros. Race Bottle Reward (Hint)"},
    [0x346942007018D] = {"@Great Bay/Zora Cape/Beaver Bros. Race HP","@Great Bay Hint/Zora Cape Hints/Beaver Bros. Race HP (Hint)"},

    -- Zora Hall
    [0x346942009001B] = {"@Great Bay/Zora Hall/Shop 1","@Great Bay Hints/Zora Hall Hints/Shop 1 (Hint)"},
    [0x346942009001C] = {"@Great Bay/Zora Hall/Shop 2","@Great Bay Hints/Zora Hall Hints/Shop 2 (Hint)"},
    [0x346942009001D] = {"@Great Bay/Zora Hall/Shop 3","@Great Bay Hints/Zora Hall Hints/Shop 3 (Hint)"},
    [0x346942009015C] = {"@Great Bay/Zora Hall/Deku Scrub Purchase Green Potion","@Great Bay Hints/Zora Hall Hints/Deku Scrub Purchase Green Potion (Hint)"},
    [0x346942000009A] = {"@Great Bay/Zora Hall/Goron Scrub Trade","@Great Bay Hints/Zora Hall Hints/Goron Scrub Trade (Hint)"},
    [0x3469420054C1E] = {"@Great Bay/Zora Hall/Goron Scrub Trade Freestanding HP","@Great Bay Hints/Zora Hall Hints/Goron Scrub Trade Freestanding HP (Hint)"},
    [0x3469420070241] = {"@Great Bay/Zora Hall/Piano Zora Song","@Great Bay Hints/Zora Hall Hints/Piano Zora Song (Hint)"},
    [0x3469420072802] = {"@Great Bay/Zora Hall/Torches Reward","@Great Bay Hints/Zora Hall Hints/Torches Reward (Hint)"},
    [0x3469420082284] = {"@Great Bay/Zora Hall/Good Picture of Lulu","@Great Bay Hints/Zora Hall Hints/Good Picture of Lulu (Hint)"},
    [0x3469420082282] = {"@Great Bay/Zora Hall/Bad Picture of Lulu","@Great Bay Hints/Zora Hall Hints/Bad Picture of Lulu (Hint)"},

    -- Pinnacle Rock
    --[] = {"@Great Bay/Pinnacle Rock/Heart Piece","@Great Bay/Pinnacle Rock Hints/Heart Piece (Hint)"},
    [0x3469420062502] = {"@Great Bay/Pinnacle Rock/Upper Eel Chest","@Great Bay Hints/Pinnacle Rock Hints/Upper Eel Chest (Hint)"},
    [0x3469420062501] = {"@Great Bay/Pinnacle Rock/Lower Eel Chest","@Great Bay Hints/Pinnacle Rock Hints/Lower Eel Chest (Hint)"},

    -- Pirates' Fortress
    [0x3469420063B00] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Exterior Underwater Log Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Exterior Underwater Log Chest (Hint)"},
    [0x3469420063B01] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Exterior Underwater Near Entrance Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Exterior Underwater Near Entrance Chest (Hint)"},
    [0x3469420063B02] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Exterior Underwater Corner Near Fortress Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Exterior Underwater Corner Near Fortress Chest (Hint)"},
    [0x346942005230C] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Sewers Cage HP","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Sewers Cage HP (Hint)"},
    [0x3469420062301] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Sewers Push Block Maze Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Sewers Push Block Maze Chest (Hint)"},
    [0x3469420062304] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Sewers Underwater Lower Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Sewers Underwater Lower Chest (Hint)"},
    [0x3469420062306] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Sewers Underwater Upper Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Sewers Underwater Upper Chest (Hint)"},
    [0x3469420062300] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Near Egg Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Near Egg Chest (Hint)"},
    [0x3469420062303] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Pirates Surrounding Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Pirates Surrounding Chest (Hint)"},
    [0x3469420061400] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Hub Lower Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Hub Lower Chest (Hint)"},
    [0x3469420061401] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Hub Upper Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Hub Upper Chest (Hint)"},
    [0x3469420062302] = {"@Dungeons/Pirates' Fortress/Pirates' Fortress Leader's Room Chest","@Dungeons Hints/Pirates' Hideout Hints/Pirates' Fortress Leader's Room Chest (Hint)"},

    -- Ocean Spider House
    [0x346942006280C] = {"@Dungeons/Ocean Spider House/Ramp Upper Token","@Dungeons Hints/Ocean Spider House Hints/Ramp Upper Token (Hint)"},
    [0x346942006280D] = {"@Dungeons/Ocean Spider House/Ramp Lower Token","@Dungeons Hints/Ocean Spider House Hints/Ramp Lower Token (Hint)"},
    [0x346942006280F] = {"@Dungeons/Ocean Spider House/Lobby Ceiling Token","@Dungeons Hints/Ocean Spider House Hints/Lobby Ceiling Token (Hint)"},
    [0x3469420062806] = {"@Dungeons/Ocean Spider House/First Room Rafter Token","@Dungeons Hints/Ocean Spider House Hints/First Room Rafter Token (Hint)"},
    [0x3469420062818] = {"@Dungeons/Ocean Spider House/First Room Open Pot #1 Token","@Dungeons Hints/Ocean Spider House Hints/First Room Open Pot #1 Token (Hint)"},
    [0x3469420062817] = {"@Dungeons/Ocean Spider House/First Room Open Pot #2 Token","@Dungeons Hints/Ocean Spider House Hints/First Room Open Pot #2 Token (Hint)"},
    [0x346942006281D] = {"@Dungeons/Ocean Spider House/First Room Wall Token","@Dungeons Hints/Ocean Spider House Hints/First Room Wall Token (Hint)"},
    [0x3469420062804] = {"@Dungeons/Ocean Spider House/Library Top Bookcase Token","@Dungeons Hints/Ocean Spider House Hints/Library Top Bookcase Token (Hint)"},
    [0x346942006281C] = {"@Dungeons/Ocean Spider House/Library Passage Behind Bookcase Front Token","@Dungeons Hints/Ocean Spider House Hints/Library Passage Behind Bookcase Front Token (Hint)"},
    [0x3469420062815] = {"@Dungeons/Ocean Spider House/Library Passage Behind Bookcase Rear Token","@Dungeons Hints/Ocean Spider House Hints/Library Passage Behind Bookcase Rear Token (Hint)"},
    [0x3469420062814] = {"@Dungeons/Ocean Spider House/Library Painting #1 Token","@Dungeons Hints/Ocean Spider House Hints/Library Painting #1 Token (Hint)"},
    [0x3469420062802] = {"@Dungeons/Ocean Spider House/Library Painting #2 Token","@Dungeons Hints/Ocean Spider House Hints/Library Painting #2 Token (Hint)"},
    [0x3469420062808] = {"@Dungeons/Ocean Spider House/Library Rafter Token","@Dungeons Hints/Ocean Spider House Hints/Library Rafter Token (Hint)"},
    [0x3469420062803] = {"@Dungeons/Ocean Spider House/Library Bookshelf Hole Token","@Dungeons Hints/Ocean Spider House Hints/Library Bookshelf Hole Token (Hint)"},
    [0x3469420062805] = {"@Dungeons/Ocean Spider House/First Room Downstairs Rafter Token","@Dungeons Hints/Ocean Spider House Hints/First Room Downstairs Rafter Token (Hint)"},
    [0x346942006281B] = {"@Dungeons/Ocean Spider House/First Room Downstairs Open Pot Token","@Dungeons Hints/Ocean Spider House Hints/First Room Downstairs Open Pot Token (Hint)"},
    [0x346942006281E] = {"@Dungeons/Ocean Spider House/First Room Downstairs Behind Staircase Token","@Dungeons Hints/Ocean Spider House Hints/First Room Downstairs Behind Staircase Token (Hint)"},
    [0x346942006280B] = {"@Dungeons/Ocean Spider House/First Room Downstairs Breakable Pot Token","@Dungeons Hints/Ocean Spider House Hints/First Room Downstairs Breakable Pot Token (Hint)"},
    [0x346942006280E] = {"@Dungeons/Ocean Spider House/First Room Downstairs Wall Token","@Dungeons Hints/Ocean Spider House Hints/First Room Downstairs Wall Token (Hint)"},
    [0x3469420062819] = {"@Dungeons/Ocean Spider House/Dining Room Open Pot Token","@Dungeons Hints/Ocean Spider House Hints/Dining Room Open Pot Token (Hint)"},
    [0x3469420062813] = {"@Dungeons/Ocean Spider House/Dining Room Painting Token","@Dungeons Hints/Ocean Spider House Hints/Dining Room Painting Token (Hint)"},
    [0x3469420062807] = {"@Dungeons/Ocean Spider House/Dining Room Ceiling Token","@Dungeons Hints/Ocean Spider House Hints/Dining Room Ceiling Token (Hint)"},
    [0x3469420062810] = {"@Dungeons/Ocean Spider House/Dining Room Chandelier #1 Token","@Dungeons Hints/Ocean Spider House Hints/Dining Room Chandelier #1 Token (Hint)"},
    [0x3469420062811] = {"@Dungeons/Ocean Spider House/Dining Room Chandelier #2 Token","@Dungeons Hints/Ocean Spider House Hints/Dining Room Chandelier #2 Token (Hint)"},
    [0x3469420062812] = {"@Dungeons/Ocean Spider House/Dining Room Chandelier #3 Token","@Dungeons Hints/Ocean Spider House Hints/Dining Room Chandelier #3 Token (Hint)"},
    [0x3469420062809] = {"@Dungeons/Ocean Spider House/Storage Room Web Token","@Dungeons Hints/Ocean Spider House Hints/Storage Room Web Token (Hint)"},
    [0x3469420062801] = {"@Dungeons/Ocean Spider House/Storage Room North Wall Token","@Dungeons Hints/Ocean Spider House Hints/Storage Room North Wall Token (Hint)"},
    [0x3469420062816] = {"@Dungeons/Ocean Spider House/Storage Room Crate Token","@Dungeons Hints/Ocean Spider House Hints/Storage Room Crate Token (Hint)"},
    [0x346942006280A] = {"@Dungeons/Ocean Spider House/Storage Room Hidden Hole Token","@Dungeons Hints/Ocean Spider House Hints/Storage Room Hidden Hole Token (Hint)"},
    [0x346942006281A] = {"@Dungeons/Ocean Spider House/Storage Room Ceiling Pot Token","@Dungeons Hints/Ocean Spider House Hints/Storage Room Ceiling Pot Token (Hint)"},
    [0x3469420062800] = {"@Dungeons/Ocean Spider House/Coloured Mask Sequence HP","@Dungeons Hints/Ocean Spider House Hints/Coloured Mask Sequence HP (Hint)"},
    [0x3469420000009] = {"@Dungeons/Ocean Spider House/Ocean Spider House Reward","@Dungeons Hints/Ocean Spider House Hints/Ocean Spider House Reward (Hint)"},

    -- Great Bay Temple
    [0x3469420064918] = {"@Dungeons/Great Bay Temple/Four Torches Chest","@Dungeons Hints/Great Bay Temple Hints/Four Torches Chest (Hint)"},
    [0x3469420014932] = {"@Dungeons/Great Bay Temple/Waterwheel Room Skulltula SF","@Dungeons Hints/Great Bay Temple Hints/Waterwheel Room Skulltula SF (Hint)"},
    [0x3469420014930] = {"@Dungeons/Great Bay Temple/Waterwheel Room Bubble Under Platform SF","@Dungeons Hints/Great Bay Temple Hints/Waterwheel Room Bubble Under Platform SF (Hint)"},
    [0x346942001491C] = {"@Dungeons/Great Bay Temple/Blender Room Barrel SF","@Dungeons Hints/Great Bay Temple Hints/Blender Room Barrel SF (Hint)"},
    [0x346942001491B] = {"@Dungeons/Great Bay Temple/Pot At Bottom Of Blender SF","@Dungeons Hints/Great Bay Temple Hints/Pot At Bottom Of Blender SF (Hint)"},
    [0x346942006491D] = {"@Dungeons/Great Bay Temple/Red-Green Pipe First Room Chest","@Dungeons Hints/Great Bay Temple Hints/Red-Green Pipe First Room Chest (Hint)"},
    [0x346942001491E] = {"@Dungeons/Great Bay Temple/Red-Green Pipe First Room Pot SF","@Dungeons Hints/Great Bay Temple Hints/Red-Green Pipe First Room Pot SF (Hint)"},
    [0x3469420064919] = {"@Dungeons/Great Bay Temple/Bio-Baba Hall Chest","@Dungeons Hints/Great Bay Temple Hints/Bio-Baba Hall Chest (Hint)"},
    [0x346942006491C] = {"@Dungeons/Great Bay Temple/Froggy Entrance Room Upper Chest","@Dungeons Hints/Great Bay Temple Hints/Froggy Entrance Room Upper Chest (Hint)"},
    [0x3469420064901] = {"@Dungeons/Great Bay Temple/Froggy Entrance Room Underwater Chest","@Dungeons Hints/Great Bay Temple Hints/Froggy Entrance Room Underwater Chest (Hint)"},
    [0x346942006491E] = {"@Dungeons/Great Bay Temple/Froggy Entrance Room Caged Chest","@Dungeons Hints/Great Bay Temple Hints/Froggy Entrance Room Caged Chest (Hint)"},
    [0x346942001491D] = {"@Dungeons/Great Bay Temple/Froggy Entrance Room Pot SF","@Dungeons Hints/Great Bay Temple Hints/Froggy Entrance Room Pot SF (Hint)"},
    [0x346942006491B] = {"@Dungeons/Great Bay Temple/Behind Locked Door Chest","@Dungeons Hints/Great Bay Temple Hints/Behind Locked Door Chest (Hint)"},
    [0x3469420064915] = {"@Dungeons/Great Bay Temple/Room Behind Waterfall Ceiling Chest","@Dungeons Hints/Great Bay Temple Hints/Room Behind Waterfall Ceiling Chest (Hint)"},
    [0x3469420064914] = {"@Dungeons/Great Bay Temple/Green Pipe Freezable Waterwheel Upper Chest","@Dungeons Hints/Great Bay Temple Hints/Green Pipe Freezable Waterwheel Upper Chest (Hint)"},
    [0x3469420064917] = {"@Dungeons/Great Bay Temple/Green Pipe Freezable Waterwheel Lower Chest","@Dungeons Hints/Great Bay Temple Hints/Green Pipe Freezable Waterwheel Lower Chest (Hint)"},
    [0x346942001491A] = {"@Dungeons/Great Bay Temple/Seesaw Room Underwater Barrel SF","@Dungeons Hints/Great Bay Temple Hints/Seesaw Room Underwater Barrel SF (Hint)"},
    [0x3469420064916] = {"@Dungeons/Great Bay Temple/Seesaw Room Chest","@Dungeons Hints/Great Bay Temple Hints/Seesaw Room Chest (Hint)"},
    [0x3469420014931] = {"@Dungeons/Great Bay Temple/Before Boss Room Underneath Platform Bubble SF","@Dungeons Hints/Great Bay Temple Hints/Before Boss Room Underneath Platform Bubble SF (Hint)"},
    [0x346942001492F] = {"@Dungeons/Great Bay Temple/Before Boss Room Exit Tunnel Bubble SF","@Dungeons Hints/Great Bay Temple Hints/Before Boss Room Exit Tunnel Bubble SF (Hint)"},
    [0x3469420055F00] = {"@Dungeons/Great Bay Temple/Heart Container","@Dungeons Hints/Great Bay Temple Hints/Heart Container (Hint)"},
    [0x3469420000057] = {"@Dungeons/Great Bay Temple/Gyorg's Remains","@Dungeons Hints/Great Bay Temple Hints/Gyorg's Remains (Hint)"},

    -- Road to Ikana
    [0x3469420065300] = {"@Ikana/Road to Ikana Pillar Chest/Road to Ikana Pillar Chest","@Ikana Hints/Road to Ikana Pillar Chest Hints/Road to Ikana Pillar Chest (Hint)"},
    [0x3469420060716] = {"@Ikana/Road to Ikana Rock Grotto Chest/Road to Ikana Rock Grotto Chest","@Ikana Hints/Road to Ikana Rock Grotto Chest Hints/Road to Ikana Rock Grotto Chest (Hint)"},
    [0x346942000008B] = {"@Ikana/Road to Ikana Stone Soldier/Road to Ikana Stone Soldier","@Ikana Hints/Road to Ikana Stone Soldier Hints/Road to Ikana Stone Soldier (Hint)"},

    -- Graveyard
    [0x3469420060718] = {"@Ikana/Graveyard/Bombable Grotto Chest","@Ikana Hints/Graveyard Hints/Bombable Grotto Chest (Hint)"},
    [0x3469420060C03] = {"@Ikana/Graveyard/Day 1 Bats Chest","@Ikana Hints/Graveyard Hints/Day 1 Bats Chest (Hint)"},
    [0x34694200000A2] = {"@Ikana/Graveyard/Day 1 Iron Knuckle Song","@Ikana Hints/Graveyard Hints/Day 1 Iron Knuckle Song (Hint)"},
    [0x3469420060C00] = {"@Ikana/Graveyard/Day 2 Iron Knuckle Chest","@Ikana Hints/Graveyard Hints/Day 2 Iron Knuckle Chest (Hint)"},
    [0x3469420063000] = {"@Ikana/Graveyard/Day 3 Dampe Big Poe Chest","@Ikana Hints/Graveyard Hints/Day 3 Dampe Big Poe Chest (Hint)"},
    [0x3469420064300] = {"@Ikana/Graveyard/Sonata To Wake Sleeping Skeleton Chest","@Ikana Hints/Graveyard Hints/Sonata To Wake Sleeping Skeleton Chest (Hint)"},

    -- Secret Shrine
    [0x3469420066000] = {"@Dungeons/Secret Shrine/Left Chest","Dungeons Hints/Secret Shrine Hints/Left Chest (Hint)"},
    [0x3469420066001] = {"@Dungeons/Secret Shrine/Middle-Left Chest","Dungeons Hints/Secret Shrine Hints/Middle-Left Chest (Hint)"},
    [0x3469420066002] = {"@Dungeons/Secret Shrine/Middle-Right Chest","Dungeons Hints/Secret Shrine Hints/Middle-Right Chest (Hint)"},
    [0x3469420066003] = {"@Dungeons/Secret Shrine/Right Chest","Dungeons Hints/Secret Shrine Hints/Right Chest (Hint)"},
    [0x346942006600A] = {"@Dungeons/Secret Shrine/Center Chest","Dungeons Hints/Secret Shrine Hints/Center Chest (Hint)"},

    -- Ikana Canyon
    [0x3469420060714] = {"@Ikana/Ikana Canyon/Grotto Chest","@Ikana Hints/Ikana Canyon Hints/Grotto Chest (Hint)"},
    [0x346942009015D] = {"@Ikana/Ikana Canyon/Deku Scrub Purchase Blue Potion","@Ikana Hints/Ikana Canyon Hints/Deku Scrub Purchase Blue Potion (Hint)"},
    [0x346942005131E] = {"@Ikana/Ikana Canyon/Zora Trade Freestanding HP","@Ikana Hints/Ikana Canyon Hints/Zora Trade Freestanding HP (Hint)"},
    [0x34694200000B9] = {"@Ikana/Ikana Canyon/Stone Tower Map Purchase","@Ikana Hints/Ikana Canyon Hints/Stone Tower Map Purchase (Hint)"},
    [0x3469420000087] = {"@Ikana/Ikana Canyon/Music Box Mummy","@Ikana Hints/Ikana Canyon Hints/Music Box Mummy (Hint)"},
    [0x34694200701DE] = {"@Ikana/Ikana Canyon/Spirit House","@Ikana Hints/Ikana Canyon Hints/Spirit House (Hint)"},
    [0x3469420030004] = {"@Ikana/Ikana Canyon/Stone Tower Great Fairy Reward","@Ikana Hints/Ikana Canyon Hints/Stone Tower Great Fairy Reward (Hint)"},

    -- Beneath the Well
    [0x3469420BEEF17] = {"@Dungeons/Beneath the Well/Cow","@Dungeons Hints/Beneath the Well Hints/Cow (Hint)"},
    [0x3469420064B02] = {"@Dungeons/Beneath the Well/Invisible Chest","@Dungeons Hints/Beneath the Well Hints/Invisible Chest (Hint)"},
    [0x3469420064B01] = {"@Dungeons/Beneath the Well/Rightside Torch Chest","@Dungeons Hints/Beneath the Well Hints/Rightside Torch Chest (Hint)"},
    [0x3469420064B1B] = {"@Dungeons/Beneath the Well/Final Chest","@Dungeons Hints/Beneath the Well Hints/Final Chest (Hint)"},

    -- Ikana Castle
    [0x3469420051D0A] = {"@Dungeons/Ikana Castle/Pillar Freestanding HP","@Dungeons Hints/Ikana Castle Hints/Pillar Freestanding HP (Hint)"},
    [0x3469420040064] = {"@Dungeons/Ikana Castle/King Song","@Dungeons Hints/Ikana Castle Hints/King Song (Hint)"},

    -- Inverted Stone Tower
    [0x346942006591F] = {"@Ikana/Inverted Stone Tower/Outside Left Chest","@Ikana Hints/Inverted Stone Tower Hints/Outside Left Chest (Hint)"},
    [0x346942006591E] = {"@Ikana/Inverted Stone Tower/Outside Middle Chest","@Ikana Hints/Inverted Stone Tower Hints/Outside Middle Chest (Hint)"},
    [0x346942006591D] = {"@Ikana/Inverted Stone Tower/Outside Right Chest","@Ikana Hints/Inverted Stone Tower Hints/Outside Right Chest (Hint)"},

    -- Stone Tower Temple
    [0x3469420061616] = {"@Dungeons/Stone Tower Temple/Entrance Room Eye Switch Chest","@Dungeons Hints/Stone Tower Temple Hints/Entrance Room Eye Switch Chest (Hint)"},
    [0x3469420061612] = {"@Dungeons/Stone Tower Temple/Entrance Room Lower Chest","@Dungeons Hints/Stone Tower Temple Hints/Entrance Room Lower Chest (Hint)"},
    [0x346942006161D] = {"@Dungeons/Stone Tower Temple/Armos Room Back Chest","@Dungeons Hints/Stone Tower Temple Hints/Armos Room Back Chest (Hint)"},
    [0x3469420061615] = {"@Dungeons/Stone Tower Temple/Armos Room Upper Chest","@Dungeons Hints/Stone Tower Temple Hints/Armos Room Upper Chest (Hint)"},
    [0x3469420061602] = {"@Dungeons/Stone Tower Temple/Armos Room Lava Chest","@Dungeons Hints/Stone Tower Temple Hints/Armos Room Lava Chest (Hint)"},
    [0x3469420061618] = {"@Dungeons/Stone Tower Temple/Eyegore Room Switch Chest","@Dungeons Hints/Stone Tower Temple Hints/Eyegore Room Switch Chest (Hint)"},
    [0x3469420061601] = {"@Dungeons/Stone Tower Temple/Eyegore Room Dexi Hand Ledge Chest","@Dungeons Hints/Stone Tower Temple Hints/Eyegore Room Dexi Hand Ledge Chest (Hint)"},
    [0x3469420061617] = {"@Dungeons/Stone Tower Temple/Eastern Water Room Underwater Chest","@Dungeons Hints/Stone Tower Temple Hints/Eastern Water Room Underwater Chest (Hint)"},
    [0x346942006161C] = {"@Dungeons/Stone Tower Temple/Eastern Water Room Sun Block Chest","@Dungeons Hints/Stone Tower Temple Hints/Eastern Water Room Sun Block Chest (Hint)"},
    [0x346942006160B] = {"@Dungeons/Stone Tower Temple/Mirror Room Sun Block Chest","@Dungeons Hints/Stone Tower Temple Hints/Mirror Room Sun Block Chest (Hint)"},
    [0x346942006160F] = {"@Dungeons/Stone Tower Temple/Mirror Room Sun Face Chest","@Dungeons Hints/Stone Tower Temple Hints/Mirror Room Sun Face Chest (Hint)"},
    [0x3469420061619] = {"@Dungeons/Stone Tower Temple/Air Gust Room Side Chest","@Dungeons Hints/Stone Tower Temple Hints/Air Gust Room Side Chest (Hint)"},
    [0x346942006160D] = {"@Dungeons/Stone Tower Temple/Air Gust Room Goron Switch Chest","@Dungeons Hints/Stone Tower Temple Hints/Air Gust Room Goron Switch Chest (Hint)"},
    [0x346942006161B] = {"@Dungeons/Stone Tower Temple/Garo Master Chest","@Dungeons Hints/Stone Tower Temple Hints/Garo Master Chest (Hint)"},
    [0x3469420061614] = {"@Dungeons/Stone Tower Temple/After Garo Upside Down Chest","@Dungeons Hints/Stone Tower Temple Hints/After Garo Upside Down Chest (Hint)"},
    [0x346942006160C] = {"@Dungeons/Stone Tower Temple/Eyegore Chest","@Dungeons Hints/Stone Tower Temple Hints/Eyegore Chest (Hint)"},

    -- Inverted Stone Tower Temple
    [0x3469420061810] = {"@Dungeons/Inverted Stone Tower Temple/Entrance Room Sun Face Chest","Dungeons Hints/Inverted Stone Tower Hints/Entrance Room Sun Face Chest (Hint)"},
    [0x346942006180E] = {"@Dungeons/Inverted Stone Tower Temple/Eastern Air Gust Room Fire Chest","Dungeons Hints/Inverted Stone Tower Hints/Eastern Air Gust Room Fire Chest (Hint)"},
    [0x3469420061813] = {"@Dungeons/Inverted Stone Tower Temple/Eastern Air Gust Room Ice Eye Switch Chest","Dungeons Hints/Inverted Stone Tower Hints/Eastern Air Gust Room Ice Eye Switch Chest (Hint)"},
    [0x3469420061804] = {"@Dungeons/Inverted Stone Tower Temple/Eastern Air Gust Room Hall Floor Switch Chest","Dungeons Hints/Inverted Stone Tower Hints/Eastern Air Gust Room Hall Floor Switch Chest (Hint)"},
    [0x3469420061811] = {"@Dungeons/Inverted Stone Tower Temple/Wizzrobe Chest","Dungeons Hints/Inverted Stone Tower Hints/Wizzrobe Chest (Hint)"},
    [0x3469420061805] = {"@Dungeons/Inverted Stone Tower Temple/Death Armos Maze Chest","Dungeons Hints/Inverted Stone Tower Hints/Death Armos Maze Chest (Hint)"},
    [0x346942006181E] = {"@Dungeons/Inverted Stone Tower Temple/Gomess Chest","Dungeons Hints/Inverted Stone Tower Hints/Gomess Chest (Hint)"},
    [0x346942006181A] = {"@Dungeons/Inverted Stone Tower Temple/Eyegore Chest","Dungeons Hints/Inverted Stone Tower Hints/Eyegore Chest (Hint)"},
    [0x3469420053600] = {"@Dungeons/Inverted Stone Tower Temple/Heart Container","Dungeons Hints/Inverted Stone Tower Hints/Heart Container (Hint)"},
    [0x3469420000058] = {"@Dungeons/Inverted Stone Tower Temple/Twinmold's Remains","Dungeons Hints/Inverted Stone Tower Hints/Twinmold's Remains (Hint)"},

    -- Moon
    [0x3469420052A01] = {"@Inside the Moon/Deku Trial/Heart Piece","@Inside the Moon Hints/Deku Trial Hints/Heart Piece (Hint)"},
    [0x3469420053F01] = {"@Inside the Moon/Goron Trial/Heart Piece","@Inside the Moon Hints/Goron Trial Hints/Heart Piece (Hint)"},
    [0x3469420054701] = {"@Inside the Moon/Zora Trial/Heart Piece","@Inside the Moon Hints/Zora Trial Hints/Heart Piece (Hint)"},
    [0x3469420066601] = {"@Inside the Moon/Link Trial/Garo Master Chest","@Inside the Moon Hints/Link Trial Hints/Garo Master Chest (Hint)"},
    [0x3469420066602] = {"@Inside the Moon/Link Trial/Iron Knuckle Chest","@Inside the Moon Hints/Link Trial Hints/Iron Knuckle Chest (Hint)"},
    [0x3469420056601] = {"@Inside the Moon/Link Trial/Heart Piece","@Inside the Moon Hints/Link Trial Hints/Heart Piece (Hint)"},
    [0x346942000007B] = {"@Inside the Moon/The Moon/Trade All Masks","@Inside the Moon Hints/Link Trial Hints/Trade All Masks (Hint)"},

    -- Any Boss
    [0x3469420040065] = {"@Dungeons/Any Boss/Oath to Order","Dungeons Hints/Any Boss Hints/Oath to Order (Hint)"}
}