-- Logic
Tracker:AddLocations("locations/locations/clock_town.jsonc")
Tracker:AddLocations("locations/locations/dungeons.jsonc")
Tracker:AddLocations("locations/locations/ikana_canyon.jsonc")
Tracker:AddLocations("locations/locations/romani_ranch.jsonc")
Tracker:AddLocations("locations/locations/snowhead_temple.jsonc")
Tracker:AddLocations("locations/locations/snowhead.jsonc")
Tracker:AddLocations("locations/locations/southern_swamp.jsonc")
Tracker:AddLocations("locations/locations/swamp_spider_house.jsonc")
Tracker:AddLocations("locations/locations/termina.jsonc")
Tracker:AddLocations("locations/locations/woodfall_temple.jsonc")

-- Hints
Tracker:AddLocations("locations/hints/clock_town_hints.jsonc")
Tracker:AddLocations("locations/hints/dungeons_hints.jsonc")
Tracker:AddLocations("locations/hints/ikana_canyon_hints.jsonc")
Tracker:AddLocations("locations/hints/romani_ranch_hints.jsonc")
Tracker:AddLocations("locations/hints/snowhead_hints.jsonc")
Tracker:AddLocations("locations/hints/southern_swamp_hints.jsonc")
Tracker:AddLocations("locations/hints/swamp_spider_house_hints.jsonc")
Tracker:AddLocations("locations/hints/termina_hints.jsonc")
Tracker:AddLocations("locations/hints/woodfall_temple_hints.jsonc")