
Tracker:AddLocations("locations/locations/clock_town.json")
Tracker:AddLocations("locations/locations/dungeons.json")
Tracker:AddLocations("locations/locations/ikana_canyon.json")
Tracker:AddLocations("locations/locations/romani_ranch.json")
Tracker:AddLocations("locations/locations/southern_swamp.json")
Tracker:AddLocations("locations/locations/swamp_spider_house.json")
Tracker:AddLocations("locations/locations/termina.json")
Tracker:AddLocations("locations/locations/woodfall_temple.json")

Tracker:AddLocations("locations/hints/clock_town_hints.json")
Tracker:AddLocations("locations/hints/dungeons_hints.json")
Tracker:AddLocations("locations/hints/ikana_canyon_hints.json")
Tracker:AddLocations("locations/hints/romani_ranch_hints.json")
Tracker:AddLocations("locations/hints/southern_swamp_hints.json")
Tracker:AddLocations("locations/hints/swamp_spider_house_hints.json")
Tracker:AddLocations("locations/hints/termina_hints.json")
Tracker:AddLocations("locations/hints/woodfall_temple_hints.json")